version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "entered the pre-build phase"
  build:
    commands:
       - echo "entered the build phase"
       - mvn clean prepare-package war:exploded
  post_build:
    commands:
       - echo "entered the post-build phase"
       - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*