version: 0.2
phases:
  pre-build:
    commands:
      - echo "entered the pre-build phase"
  build:
    commands:
       - echo "entered the build phase"
       - mvn clean prepare-package war:exploded
  post-build:
    commands:
       - echo "entered the post-build phase"
       - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*